version: "3.8"

services:
  backend:
    build: ./backend
    env_file: .env
    ports: ["8000:8000"]
    volumes: ["./data:/app/data"]
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This allows access to host services like Ollama

  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    depends_on: ["backend"]
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true