version: "3.8"

services:
  backend:
    build: ./backend
    env_file: .env
    ports: ["8000:8000"]
    volumes: ["./data:/app/data"]
    restart: unless-stopped
    network_mode: "host"  # This allows direct access to localhost services like Ollama

  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    depends_on: ["backend"]
    restart: unless-stopped